---
language: python
python: "3.7"
os: linux
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - MOLECULE_DISTRO=debian:buster-slim
before_script:
  - nvm install 14
  - nvm use 14
script:
  - pipenv run molecule test

deploy:
  provider: npm
  email: labs@idealista.com
  api_key:
    secure: l9wNnh3ltt5AE/cWTJoNdRhO0Oy5yWDx3pJTlzuYgBgxvYcSFdofmgbO3pm+PfY5XGOn8bNtWS5XsN9O6DQ6RwBHul1kv9iDiZ28TnSKJZzAvCf0JfNLzxcbUvuVLgDQio186MOk4nevE2iWG+2M6Pv23scU0emGrxqYRLVJiq2wYMn4F10piezIpn9/62H/27+PnZd6rOivv6ooy4eEyLzPZLpnItBxoA56Bjh8gNPYtS+wjHstwgVAFj0HmMdQrwf4R+tINE0M6NQSdl80ejYQadbhnSj9PwGIWnE5+YJXSBku0NCKncVi2VQaDQAd3XZZ+rrirL7Gty4nelCkoRXjeT24PfNKAtdxpm4oYVWSYycDxhwtOBDup0Bojt/Tv96BNdzcNYhPWB6iPCIzuwZa7lh5f3l/cfCghgJLi1tkswO0KqmYMh/fgesOScTMSm2CUBvzL8TCx9Uf6BReVjV/UXd09wroB4ynbUZJwVb5ryTftLIfJGJpaA9TBpDGyzdz4J65K2KBZZxQ8xFWEe6x62zuTZztVP8+btqUj8HIk2/swjtTGPDLLknGeIF2cqbyn79VO/etV0pOFvsQXxLcVl834d5zQTN/Kb1RTiyU6hWCqhddpEa3jsIWFXfIF/E/FUFtXcbfXuJOmqWVZEBeb+XomBqoGCXC9JfAUFo=
  on:
    tags: true
    repo: idealista/yatm
  skip_cleanup: true

notifications:
  email:
    if: branch = master
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
