---
language: python
python: "3.7"
os: linux
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  jobs:
    - MOLECULE_DISTRO=debian:buster-slim
before_script:
  - npm install -g npm@'>=6'
script:
  - pipenv run molecule test

deploy:
  provider: npm
  email: labs@idealista.com
  api_key:
    secure: QP5udTO6gsQnznEcJj687PdDGIZ8JR1SGgpdjbkApO4IsqTz3RKQ4TSwq5T3RgrKniQ8UdI3SePeVydI5fqBIm2Is0DJEMRDLna/buB0N0jMcLGRpJVSaLMxBc/QJ8DmTh5RufRf6MKxU11sqlnVSrjyc4NOUg5yb8vYQQjvLROrqKK1pGAuveatYW3QPBdo4l2fL+cE0MPL3O/Uik4VHmETaQ7FUJSvyl06XwePCvyooXkMiQASdkC2ieEBKYA0O8O5Yw7qiL7EqA9ECVtAWlTwgxGNyWHemFgChSpyPBrdqrbKOJtnTDJfmiXdgDCfNSwaWv+2HvPlU2tN+hKHgbT+QReIw/GY1r/hhJ+NXvTzqyTqnuQDZhnBk1ysqDloMT42xEsfbPKd0xjLYMbN/vv14RMtBqm17u2cBjfZO2TFQI8ImQU1cZJfqd7vxj0gSQTnCuwmOyNpM1jVuSsMx0K+fxPhJbsGNVP6UaMwtbBWneVQb1zSyjgeWvFL+slt49ULlgX6nQH0xVy/fOluPfoNV7M9A0KfWDH3DrQ7zvkUIR8gKE340vbAf0mhQjY5NVTGmeV9v9nYA9vXEIvhb9W4XcSdBMEGG99gqyVhLJb5ygxEWYP25QaivCNvwtaOM8k8Gt6U/dgHHtXB8WMvzXpLPvGDgDfuukPS2npJH30=
  on:
    tags: true
    repo: idealista/yatm
  skip_cleanup: true

notifications:
  email:
    if: branch = master
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com
