---

- name:  YATM | Check origin libraries
  stat:
    path: "{{ playbook_dir }}/../../deps"
  delegate_to: localhost
  become: no
  register: deps

- block:

    - name:  YATM | Package remote libraries
      archive:
        path: "{{ yatm_install_path }}/deps"
        dest: "{{ yatm_install_path }}/deps.tgz"

    - name:  YATM | Copy back the libraries
      fetch:
        src: "{{ yatm_install_path }}/deps.tgz"
        dest: "{{ playbook_dir }}/../../"
        flat: yes

    - name:  YATM | Unarchive libraries
      unarchive:
        src: "{{ playbook_dir }}/../../deps.tgz"
        dest: "{{ playbook_dir }}/../../"
      delegate_to: localhost
      become: no

    - name:  YATM | Remove package
      file:
        path: "{{ playbook_dir }}/../../deps.tgz"
        state: absent
      delegate_to: localhost
      become: no

  when: deps.stat.isdir is not defined
