---

- name: YATM | Install Build Utils
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - valgrind
    - wget
    - webp

- name: YATM | Create Deps
  file:
    path: "{{ yatm_install_path }}/deps/{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - lib
    - include

- name: YATM | Include libraries
  shell: "cp -R {{ item }}* {{ yatm_install_path }}/deps/lib"
  changed_when: false
  with_items: "{{ yatm_build_libraries }}"

- name: YATM | Remove symlinks
  shell: "for f in $(find -type l);do cp --remove-destination $(readlink $f) $f;done;"
  args:
    chdir: "{{ yatm_install_path }}/deps/lib"
  changed_when: false

- name: YATM | Include headers
  shell: "cp -R  {{ item }} {{ yatm_install_path }}/deps/include"
  changed_when: false
  with_items: "{{ yatm_build_includes }}"
  tags:
    - skip_ansible_lint

- name: YATM | Install node-gyp
  npm:
    name:  node-gyp
    global: yes

- name: YATM | Link node-gyp binary
  file:
    src: "/opt/nodejs/bin/node-gyp"
    dest: "/usr/bin/node-gyp"
    state: link

- name: YATM | Copy sources
  copy:
    src: "{{ playbook_dir }}/../../{{ item }}"
    dest: "{{ yatm_install_path }}"
  with_items: "{{ yatm_build_files }}"


- name: YATM | Build
  command: "{{ item }}"
  args:
    chdir: "{{ yatm_install_path }}"
  changed_when: false
  with_items:
    - npm install --unsafe-perm
    - npm test
    - chmod +x test/memoryleak/memoryleak.sh
    - ./test/memoryleak/memoryleak.sh
